# These are supported funding model platforms

github: ahyat098 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [ahyat098]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: http://instagram.com/_ahyat098 # Replace with up to 4 custom sponsorship URLs e.g., ['http://instagram.com/_ahyat098']
